ALTER TABLE invoices ADD COLUMN IF NOT EXISTS direction VARCHAR(10) NOT NULL DEFAULT 'OUT';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'ORDER';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS file_name VARCHAR(255) NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_invoices_direction ON invoices(direction);
